Myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/login', views.LoginView.as_view(), name='login'),
    path('accounts/logout', views.LogoutView.as_view(), name='logout', kwargs={'next_page':'/'}),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('about/',views.AboutView.as_view(), name='about'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatPostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('post/<int:pk>/delete/',views.PostDeleteView.as_view(), name='post_remove'),
    path('drafts/',views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/delete/',views.comment_remove, name='comment_remove'),
    path('post/<int:pk>/publish/',views.post_publish, name='post_publish'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)


    def publish(self):
        self.published_date = timezone.now()
        self.save() 


    def approve_comments(self):
        return self.comments.filter(approve_comment=True)

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk': self.pk})
    

    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('post_list')
    

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta():
        model = Post
        fields = ('author','title','text')

        widgets = {

            'title': forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'}),
        }


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('author','text')

        widgets = {
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.urls import reverse_lazy
from .models import Post,Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView, DetailView,
                       CreateView,UpdateView, DeleteView)
# Create your views here.


class AboutView(TemplateView):
    template_name = 'about.html'


class PostListView(ListView):
    
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')


class PostDetailView(DetailView):
    model = Post


class CreatPostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm 

    model = Post


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm
    model = Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'
    success_url = reverse_lazy('post_list')

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'blog/post_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')


@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail',pk=pk)

@login_required
def add_comment_to_post (request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()

    return render(request, 'blog/comment_form.html', {'form': form})



@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('post_detail', pk=post_pk)

blog/templates/blog/about.html
{% extends "blog/base.html" %}

{% block content %}

    <hi> About Me </h1>
    <p> Thanks for visiting my blog </h1>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        <title>Blog</title>

        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        {# MEDIUM STYLE EDITOR#}
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">


        {# Custom CSS#}
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">

        {# Fonts#}
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">


    </head>
    <body>
        
        <nav class="navbar navbar-default techfont custom-navbar">
            <div class="container">
                
                <ul>
                    <li><a class='navbar-brand bigbrand' href="{% url 'blog:post_list' %}">My blog</a></li>
                    <li><a href="{% url 'blog:about' %}"> About Me</a></li>
                    <li><a href="http://www.github.com"> Github</a></li>
                    <li><a href="https://www.linkedin.com"> LinkedIn</a></li>
                </ul>

                <ul class='nav navbar-nav navbar-right'>
                    {% if user.is_authenticated %}    
                    <li>
                        <a href="{% url 'blog:post_new' %}"> New Post </a>
                    </li>

                    <li>
                        <a href="{% url 'blog:post_draft_list' %}"> Drafts </a>
                    </li>
                    
                    <li>
                        <a href="{% url 'logout' %}"> Logout </a>
                    </li>

                    <li>
                        <a>Welcome : {{user.username}}</a>
                    </li>

                        {% else %}

                        <li>
                            <a class='nav navbar-right' href= "{% url 'login'%}"><span class='glyphicon glyphicon-user'>Login </span> </a>
                        </li>
                    {% endif %}
                </ul>
            </div>   

        </nav>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    <div class="blog_posts">
                        {% block content%}

                        {% endblock%} 
                    </div>

                </div> 
            
            </div>


        </div>


    </body>


</html>

blog/templates/blog/comment_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New Comment</h1>
    <form class="post-form" method="post">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class='save btn btn-default'> Post Comment</button>
    </form>

    <script> var editor= new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p> Are you sure you want to delete {{ object }}? </p>
        <input type="submit" class='btn btn-danger' value="Confirm">
    </form>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}

<h1 class="posttitle loader">{{post.title}}</h1>
{% if post.published_date %}

    <div class="date postdate">
        {{ post.published_date }}

    </div>

{% else %}
    <a class= "btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>

{% endif %}

<p class='postcontent'>{{ post.text|safe|linebreaksbr}}</p>

{% if user.is_authenticated %}
    <a class='btn btn-primary' href="{% url 'blog:post_edit' pk=post.pk %}">
        <spam class='glyphicon-pencil'></spam>
    </a>

    <a class='btn btn-primary' href="{% url 'blog:post_remove' pk=post.pk %}">
        <spam class='glyphicon-remove'></spam>
    </a>
{% endif %}
<hr>

<a class='btn btn-primary btn-comment' href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

<div class="container">
    {% for comment in post.comments.all %}
    <br>
        {% if user.is_authenticated or comment.approved_comment %}
            {{comment.created_date }}
                {%if not comment.approved_comment %}

                <a class='btn btn-primary' href="{% url 'blog:comment_approve' pk=comment.pk %}">
                    <spam class='glyphicon-ok'></spam>
                </a>

                <a class='btn btn-default' href="{% url 'blog:comment_remove' pk=comment.pk %}">
                    <spam class='glyphicon-remove'></spam>
                </a>
                {% endif %}

                <p>{{comment.text|safe|linebreaksbr}}</p>
                <p>Posted By: <b> {{ comment.author }}</b></p>
        {% endif %}
        {% empty %}
        <p>No comment</p>
    {% endfor %}

</div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends "blog/base.html" %}

{% block content %}

    {% for post in posts %}
        <div class="post">
            <p class='date'>created: {{ post.create_date|date: 'd-m-Y'}}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
            <p> {{ post.text| truncatechars:200}}</p>
        </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block content %}
    <h1>New Post</h1>
    <form class="post-form" method="POST">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class='save btn btn-default' name="button">Save</button>
    </form>

    <script>var editor = new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}

<div class="centerstage">
    {% for post in post_list %}
    
    <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}"></a></h1>
        <div class="date">
            <p>Published on: {{post.published_date | date:"D M Y"}}</p>
        </div>
        <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{post.approved_comments.count}}</a> 

    </div>
    
    {% endfor %}


</div>


{% endblock %}